language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t divmakkar/docker-react-1 -f Dockerfile.dev .

script:
  - docker run -e CI=true divmakkar/docker-react-1 npm run test